export * from './payments.component';
export * from "./payments-method.component";
export * from "./payments-transfer.component";
export * from "./payments-thankyou.component";
export * from "./payments-list.component";
export * from "./payments-detail.component"
export * from "./payments-report.component"
export * from "./payments-receipt.component"
export * from "./payments-paypal.component"